# Generated by Django 5.1.1 on 2025-03-04 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_connection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUserModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_user_id', models.CharField(max_length=255)),
                ('facebook_user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('facebook_user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_user_access_token', models.CharField(max_length=255)),
                ('social_media_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_connection.socialmediaaccount')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_page_id', models.CharField(max_length=255)),
                ('facebook_page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('global_name_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_page_access_token', models.CharField(max_length=255)),
                ('facebook_page_picture_url', models.TextField(blank=True, null=True)),
                ('followers_count', models.BigIntegerField(blank=True, null=True)),
                ('following_count', models.BigIntegerField(blank=True, null=True)),
                ('tasks', models.JSONField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('social_media_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_connection.socialmediaaccount')),
                ('facebook_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_media.facebookusermodel')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=255)),
                ('instagram_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_access_token', models.CharField(max_length=255)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('followers_count', models.BigIntegerField(blank=True, null=True)),
                ('following_count', models.BigIntegerField(blank=True, null=True)),
                ('social_media_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_connection.socialmediaaccount')),
            ],
        ),
    ]
