# Generated by Django 5.1.1 on 2025-03-05 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammodel',
            name='facebook_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_media.facebookpagemodel'),
        ),
    ]
