# Generated by Django 5.1.1 on 2025-03-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_media', '0003_alter_instagrammodel_instagram_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammodel',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
