# Generated by Django 5.1.1 on 2025-03-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_media', '0004_alter_instagrammodel_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammodel',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
