# Generated by Django 5.1.7 on 2025-03-21 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0010_postmodle_publish_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInteractionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('like', 'like'), ('comment', 'comment'), ('share', 'share')], default='like', max_length=30)),
                ('interaction_date', models.BigIntegerField(blank=True, null=True)),
                ('external_user_id', models.BigIntegerField(blank=True, null=True)),
                ('external_post_id', models.BigIntegerField(blank=True, null=True)),
                ('external_interaction_id', models.BigIntegerField(blank=True, null=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.postmodle')),
            ],
        ),
    ]
