# Generated by Django 5.1.1 on 2025-03-08 23:34

import core.utils.get_current_timestamp
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_connection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('application', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('published', 'Published'), ('draft', 'Draft')], default='published', max_length=15)),
                ('created_at', models.BigIntegerField(default=core.utils.get_current_timestamp.get_current_timestamp)),
                ('updated_at', models.BigIntegerField(default=core.utils.get_current_timestamp.get_current_timestamp)),
                ('likes_count', models.BigIntegerField(default=0)),
                ('comments_count', models.BigIntegerField(default=0)),
                ('shares_count', models.BigIntegerField(default=0)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts_connection.platform')),
                ('social_media_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts_connection.socialmediaaccount')),
            ],
        ),
    ]
