# Generated by Django 5.1.1 on 2025-03-09 00:58

import core.utils.get_current_timestamp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postmodle_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodle',
            name='created_at',
            field=models.BigIntegerField(default=core.utils.get_current_timestamp.get_current_timestamp),
        ),
        migrations.AlterField(
            model_name='postmodle',
            name='scheduled_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmodle',
            name='updated_at',
            field=models.BigIntegerField(default=core.utils.get_current_timestamp.get_current_timestamp),
        ),
    ]
