# Generated by Django 5.1.1 on 2025-03-09 01:09

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postmodle_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodle',
            name='created_at',
            field=models.BigIntegerField(default=posts.models.get_current_timestamp),
        ),
        migrations.AlterField(
            model_name='postmodle',
            name='updated_at',
            field=models.BigIntegerField(default=posts.models.get_current_timestamp),
        ),
    ]
