# Generated by Django 5.1.1 on 2025-03-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_postmodle_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodle',
            name='external_post_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
