# Generated by Django 5.1.1 on 2025-03-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_postmodle_external_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodle',
            name='external_post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
