# Generated by Django 5.1.1 on 2025-03-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_postmodle_external_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodle',
            name='hashtags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postmodle',
            name='links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postmodle',
            name='media_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postmodle',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
