# Generated by Django 5.1.7 on 2025-03-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postmodle_hashtags_postmodle_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodle',
            name='publish_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
