# Generated by Django 5.1.1 on 2025-03-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_connection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
