"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qly4pm5ysoem^(##_wqd2b^=_*v(-0x_w4#v1bus#+#gp-3lup'
FACEBOOK_APP_ID= '478183998355970'
FACEBOOK_APP_SECRET  = 'd9ce01b7673e4d96789012716339a1be'
FACEBOOK_GRAPH_API_VERSION = "v20.0"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
AUTH_USER_MODEL = 'user.UserModel' 


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # أو حسب مزود خدمة البريد الإلكتروني الخاص بك
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'socialmanager102@gmail.com'
EMAIL_HOST_PASSWORD = 'xryp hlkk ufdt dlek'
FRONTEND_URL = 'http://127.0.0.1:8000'  # عنوان الواجهة الأمامية حيث سيتم توجيه المستخدم
SSL_CERTIFICATE = os.path.join(BASE_DIR, 'certs', 'localhost.pem')
SSL_PRIVATE_KEY = os.path.join(BASE_DIR, 'certs', 'localhost-key.pem')

SECURE_SSL_REDIRECT = True  # تحويل جميع الطلبات إلى HTTPS
SESSION_COOKIE_SECURE = True  # تأمين ملفات تعريف الارتباط
CSRF_COOKIE_SECURE = True  # تأمين ملفات تعريف الارتباط الخاصة بـ CSRF

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    "user",
    "accounts_connection",
    "platform_media",
    "posts",
    "interactions",
    'corsheaders',
    'sslserver',
    'django_extensions',
    # 'dj_rest_auth',
    # 'dj_rest_auth.registration',
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.facebook',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'src.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',
#     'allauth.account.auth_backends.AuthenticationBackend',
# ]




# SOCIALACCOUNT_PROVIDERS  = {
#     'facebook': {
#         # For each OAuth based provider, either add a ``SocialApp``
#         # (``socialaccount`` app) containing the required client
#         # credentials, or list them here:
#         'APP': {
#             'client_id': '478183998355970',
#             'secret': 'd9ce01b7673e4d96789012716339a1be',
#             'key': ''
#         },
#         'SCOPE': [
#                         "email",
#                         "manage_fundraisers",
#                         "read_insights",
#                         "publish_video",
#                         "catalog_management",
#                         "pages_manage_cta",
#                         "pages_manage_instant_articles",
#                         "pages_show_list",
#                         "read_page_mailboxes",
#                         "ads_management",
#                         "ads_read",
#                         "business_management",
#                         "pages_messaging",
#                         "pages_messaging_subscriptions",
#                         "instagram_basic",
#                         "instagram_manage_comments",
#                         "instagram_manage_insights",
#                         "instagram_content_publish",
#                         "leads_retrieval",
#                         "whatsapp_business_management",
#                         "instagram_manage_messages",
#                         "page_events",
#                         "pages_read_engagement",
#                         "pages_manage_metadata",
#                         "pages_read_user_content",
#                         "pages_manage_ads",
#                         "pages_manage_posts",
#                         "pages_manage_engagement",
#                         "whatsapp_business_messaging",
#                         "instagram_branded_content_brand",
#                         "instagram_branded_content_creator",
#                         "instagram_branded_content_ads_brand",
#                         "instagram_manage_events",
#                         "manage_app_solution"
#                     ],
#         'AUTH_PARAMS': {
#             'auth_type': 'reauthenticate',
#         },
#         'METHOD': 'oauth2',  # طريقة المصادقة
#         'VERIFIED_EMAIL': False,  # التحقق من البريد الإلكتروني
#     }
#     }

# SITE_ID = 1

# ACCOUNT_EMAIL_VERIFICATION = 'none' 


WSGI_APPLICATION = 'src.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


CORS_ORIGIN_WHITELIST = [
    'http://localhost:5500',  # البورت الذي يشغّل HTML
    'http://127.0.0.1:8000', # خادم Django
]

CORS_ORIGIN_ALLOW_ALL = True
# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
